export const UN_MEMBER_STATE_PASSPORTS = [
  { passport: "Afghanistan", nationality: "Afghan" },
  { passport: "Albania", nationality: "Albanian" },
  { passport: "Algeria", nationality: "Algerian" },
  { passport: "Andorra", nationality: "Andorran" },
  { passport: "Angola", nationality: "Angolan" },
  { passport: "Antigua and Barbuda", nationality: "Antiguan and Barbudan", aliases: ["Antigua and Barbuda"] },
  { passport: "Argentina", nationality: "Argentine" },
  { passport: "Armenia", nationality: "Armenian" },
  { passport: "Australia", nationality: "Australian" },
  { passport: "Austria", nationality: "Austrian" },
  { passport: "Azerbaijan", nationality: "Azerbaijani" },
  { passport: "Bahamas", nationality: "Bahamian", aliases: ["Bahamas"] },
  { passport: "Bahrain", nationality: "Bahraini" },
  { passport: "Bangladesh", nationality: "Bangladeshi" },
  { passport: "Barbados", nationality: "Barbadian" },
  { passport: "Belarus", nationality: "Belarusian" },
  { passport: "Belgium", nationality: "Belgian" },
  { passport: "Belize", nationality: "Belizean" },
  { passport: "Benin", nationality: "Beninese" },
  { passport: "Bhutan", nationality: "Bhutanese" },
  { passport: "Bolivia", nationality: "Bolivian" },
  { passport: "Bosnia and Herzegovina", nationality: "Bosnia and Herzegovina", aliases: ["Bosnian and Herzegovinian"] },
  { passport: "Botswana", nationality: "Botswana", aliases: ["Motswana"] },
  { passport: "Brazil", nationality: "Brazilian" },
  { passport: "Brunei", nationality: "Bruneian", aliases: ["Brunei"] },
  { passport: "Bulgaria", nationality: "Bulgarian" },
  { passport: "Burkina Faso", nationality: "Burkinabe", aliases: ["Burkina Faso"] },
  { passport: "Burundi", nationality: "Burundian" },
  { passport: "Cabo Verde", nationality: "Cape Verdean", aliases: ["Cabo Verdean", "Cape Verde"] },
  { passport: "Cambodia", nationality: "Cambodian" },
  { passport: "Cameroon", nationality: "Cameroonian" },
  { passport: "Canada", nationality: "Canadian" },
  { passport: "Central African Republic", nationality: "Central African" },
  { passport: "Chad", nationality: "Chadian" },
  { passport: "Chile", nationality: "Chilean" },
  { passport: "China", nationality: "Chinese" },
  { passport: "Colombia", nationality: "Colombian" },
  { passport: "Comoros", nationality: "Comorian" },
  { passport: "Republic of the Congo", nationality: "Republic of the Congo", aliases: ["Congolese"] },
  { passport: "Costa Rica", nationality: "Costa Rican" },
  { passport: "Cote d'Ivoire", nationality: "Ivorian", aliases: ["Cote d'Ivoire", "Ivory Coast"] },
  { passport: "Croatia", nationality: "Croatian" },
  { passport: "Cuba", nationality: "Cuban" },
  { passport: "Cyprus", nationality: "Cypriot" },
  { passport: "Czechia", nationality: "Czech", aliases: ["Czech Republic"] },
  { passport: "Democratic Republic of the Congo", nationality: "Democratic Republic of the Congo", aliases: ["DR Congo"] },
  { passport: "Denmark", nationality: "Danish" },
  { passport: "Djibouti", nationality: "Djiboutian" },
  { passport: "Dominica", nationality: "Dominica" },
  { passport: "Dominican Republic", nationality: "Dominican Republic", aliases: ["Dominican"] },
  { passport: "Ecuador", nationality: "Ecuadorian" },
  { passport: "Egypt", nationality: "Egyptian" },
  { passport: "El Salvador", nationality: "Salvadoran", aliases: ["El Salvador"] },
  { passport: "Equatorial Guinea", nationality: "Equatoguinean", aliases: ["Equatorial Guinean"] },
  { passport: "Eritrea", nationality: "Eritrean" },
  { passport: "Estonia", nationality: "Estonian" },
  { passport: "Eswatini", nationality: "Eswatini", aliases: ["Swazi", "Swaziland"] },
  { passport: "Ethiopia", nationality: "Ethiopian" },
  { passport: "Fiji", nationality: "Fijian" },
  { passport: "Finland", nationality: "Finnish" },
  { passport: "France", nationality: "French" },
  { passport: "Gabon", nationality: "Gabonese" },
  { passport: "Gambia", nationality: "Gambian", aliases: ["The Gambia"] },
  { passport: "Georgia", nationality: "Georgian" },
  { passport: "Germany", nationality: "German" },
  { passport: "Ghana", nationality: "Ghanaian" },
  { passport: "Greece", nationality: "Greek" },
  { passport: "Grenada", nationality: "Grenadian" },
  { passport: "Guatemala", nationality: "Guatemalan" },
  { passport: "Guinea", nationality: "Guinean" },
  { passport: "Guinea-Bissau", nationality: "Bissau-Guinean", aliases: ["Guinea-Bissau"] },
  { passport: "Guyana", nationality: "Guyanese" },
  { passport: "Haiti", nationality: "Haitian" },
  { passport: "Honduras", nationality: "Honduran" },
  { passport: "Hungary", nationality: "Hungarian" },
  { passport: "Iceland", nationality: "Icelandic" },
  { passport: "India", nationality: "Indian" },
  { passport: "Indonesia", nationality: "Indonesian" },
  { passport: "Iran", nationality: "Iranian" },
  { passport: "Iraq", nationality: "Iraqi" },
  { passport: "Ireland", nationality: "Irish" },
  { passport: "Israel", nationality: "Israeli" },
  { passport: "Italy", nationality: "Italian" },
  { passport: "Jamaica", nationality: "Jamaican" },
  { passport: "Japan", nationality: "Japanese" },
  { passport: "Jordan", nationality: "Jordanian" },
  { passport: "Kazakhstan", nationality: "Kazakhstani", aliases: ["Kazakh"] },
  { passport: "Kenya", nationality: "Kenyan" },
  { passport: "Kiribati", nationality: "Kiribati", aliases: ["I-Kiribati"] },
  { passport: "Kuwait", nationality: "Kuwaiti" },
  { passport: "Kyrgyzstan", nationality: "Kyrgyzstani", aliases: ["Kyrgyz"] },
  { passport: "Laos", nationality: "Lao", aliases: ["Laotian", "Laos"] },
  { passport: "Latvia", nationality: "Latvian" },
  { passport: "Lebanon", nationality: "Lebanese" },
  { passport: "Lesotho", nationality: "Lesotho", aliases: ["Basotho"] },
  { passport: "Liberia", nationality: "Liberian" },
  { passport: "Libya", nationality: "Libyan" },
  { passport: "Liechtenstein", nationality: "Liechtenstein", aliases: ["Liechtensteiner"] },
  { passport: "Lithuania", nationality: "Lithuanian" },
  { passport: "Luxembourg", nationality: "Luxembourgish" },
  { passport: "Madagascar", nationality: "Malagasy", aliases: ["Madagascan"] },
  { passport: "Malawi", nationality: "Malawian" },
  { passport: "Malaysia", nationality: "Malaysian" },
  { passport: "Maldives", nationality: "Maldivian" },
  { passport: "Mali", nationality: "Malian" },
  { passport: "Malta", nationality: "Maltese" },
  { passport: "Marshall Islands", nationality: "Marshallese", aliases: ["Marshall Islands"] },
  { passport: "Mauritania", nationality: "Mauritanian" },
  { passport: "Mauritius", nationality: "Mauritian" },
  { passport: "Mexico", nationality: "Mexican" },
  { passport: "Micronesia", nationality: "Micronesian", aliases: ["Federated States of Micronesia"] },
  { passport: "Moldova", nationality: "Moldovan" },
  { passport: "Monaco", nationality: "Monegasque", aliases: ["Monaco"] },
  { passport: "Mongolia", nationality: "Mongolian" },
  { passport: "Montenegro", nationality: "Montenegrin" },
  { passport: "Morocco", nationality: "Moroccan" },
  { passport: "Mozambique", nationality: "Mozambican" },
  { passport: "Myanmar", nationality: "Myanmar", aliases: ["Burmese"] },
  { passport: "Namibia", nationality: "Namibian" },
  { passport: "Nauru", nationality: "Nauruan" },
  { passport: "Nepal", nationality: "Nepalese", aliases: ["Nepali"] },
  { passport: "Netherlands", nationality: "Dutch", aliases: ["Netherlands"] },
  { passport: "New Zealand", nationality: "New Zealand", aliases: ["New Zealander"] },
  { passport: "Nicaragua", nationality: "Nicaraguan" },
  { passport: "Niger", nationality: "Nigerien" },
  { passport: "Nigeria", nationality: "Nigerian" },
  { passport: "North Korea", nationality: "North Korean" },
  { passport: "North Macedonia", nationality: "North Macedonian", aliases: ["Macedonian"] },
  { passport: "Norway", nationality: "Norwegian" },
  { passport: "Oman", nationality: "Omani" },
  { passport: "Pakistan", nationality: "Pakistani" },
  { passport: "Palau", nationality: "Palauan" },
  {
    passport: "Palestine",
    nationality: "Palestinian",
    aliases: ["State of Palestine"],
    pageTitle: "Visa requirements for Palestinian citizens",
  },
  { passport: "Panama", nationality: "Panamanian" },
  { passport: "Papua New Guinea", nationality: "Papua New Guinean" },
  { passport: "Paraguay", nationality: "Paraguayan" },
  { passport: "Peru", nationality: "Peruvian" },
  { passport: "Philippines", nationality: "Philippine", aliases: ["Filipino"] },
  { passport: "Poland", nationality: "Polish" },
  { passport: "Portugal", nationality: "Portuguese" },
  { passport: "Qatar", nationality: "Qatari" },
  { passport: "Romania", nationality: "Romanian" },
  { passport: "Russia", nationality: "Russian" },
  { passport: "Rwanda", nationality: "Rwandan" },
  { passport: "Saint Kitts and Nevis", nationality: "Kittitian and Nevisian", aliases: ["Saint Kitts and Nevis"] },
  { passport: "Saint Lucia", nationality: "Saint Lucian" },
  { passport: "Saint Vincent and the Grenadines", nationality: "Saint Vincent and the Grenadines", aliases: ["Vincentian"] },
  { passport: "Samoa", nationality: "Samoan" },
  { passport: "San Marino", nationality: "Sammarinese", aliases: ["San Marino"] },
  { passport: "Sao Tome and Principe", nationality: "Santomean", aliases: ["Sao Tomean", "Sao Tome and Principe"] },
  { passport: "Saudi Arabia", nationality: "Saudi" },
  { passport: "Senegal", nationality: "Senegalese" },
  { passport: "Serbia", nationality: "Serbian" },
  { passport: "Seychelles", nationality: "Seychellois" },
  { passport: "Sierra Leone", nationality: "Sierra Leonean" },
  { passport: "Singapore", nationality: "Singaporean" },
  { passport: "Slovakia", nationality: "Slovak" },
  { passport: "Slovenia", nationality: "Slovenian" },
  { passport: "Solomon Islands", nationality: "Solomon Islands", aliases: ["Solomon Islander"] },
  { passport: "Somalia", nationality: "Somali" },
  { passport: "South Africa", nationality: "South African" },
  { passport: "South Korea", nationality: "South Korean" },
  { passport: "South Sudan", nationality: "South Sudanese" },
  { passport: "Spain", nationality: "Spanish" },
  { passport: "Sri Lanka", nationality: "Sri Lankan" },
  { passport: "Sudan", nationality: "Sudanese" },
  { passport: "Suriname", nationality: "Surinamese" },
  { passport: "Sweden", nationality: "Swedish" },
  { passport: "Switzerland", nationality: "Swiss" },
  { passport: "Syria", nationality: "Syrian" },
  { passport: "Tajikistan", nationality: "Tajik" },
  { passport: "Tanzania", nationality: "Tanzanian" },
  { passport: "Thailand", nationality: "Thai" },
  { passport: "Timor-Leste", nationality: "East Timorese", aliases: ["Timorese", "Timor-Leste"] },
  { passport: "Togo", nationality: "Togolese" },
  { passport: "Tonga", nationality: "Tongan" },
  { passport: "Trinidad and Tobago", nationality: "Trinidad and Tobago", aliases: ["Trinidadian and Tobagonian"] },
  { passport: "Tunisia", nationality: "Tunisian" },
  { passport: "Turkey", nationality: "Turkish" },
  { passport: "Turkmenistan", nationality: "Turkmen" },
  { passport: "Tuvalu", nationality: "Tuvaluan" },
  { passport: "Uganda", nationality: "Ugandan" },
  { passport: "Ukraine", nationality: "Ukrainian" },
  { passport: "United Arab Emirates", nationality: "Emirati", aliases: ["United Arab Emirates"] },
  { passport: "United Kingdom", nationality: "British", aliases: ["United Kingdom"] },
  { passport: "United States", nationality: "United States", aliases: ["American"] },
  { passport: "Uruguay", nationality: "Uruguayan" },
  { passport: "Uzbekistan", nationality: "Uzbekistani", aliases: ["Uzbek"] },
  { passport: "Vanuatu", nationality: "Vanuatuan" },
  { passport: "Venezuela", nationality: "Venezuelan" },
  { passport: "Vietnam", nationality: "Vietnamese" },
  { passport: "Yemen", nationality: "Yemeni" },
  { passport: "Zambia", nationality: "Zambian" },
  { passport: "Zimbabwe", nationality: "Zimbabwean" },
];
