const COUNTRY_CODES = {
  "afghanistan": "AF",
  "albania": "AL",
  "algeria": "DZ",
  "andorra": "AD",
  "angola": "AO",
  "antigua and barbuda": "AG",
  "argentina": "AR",
  "armenia": "AM",
  "australia": "AU",
  "australia and territories": "AU",
  "austria": "AT",
  "azerbaijan": "AZ",
  "bahamas": "BS",
  "the bahamas": "BS",
  "bahrain": "BH",
  "bangladesh": "BD",
  "barbados": "BB",
  "belarus": "BY",
  "belgium": "BE",
  "belize": "BZ",
  "benin": "BJ",
  "bhutan": "BT",
  "bolivia": "BO",
  "bosnia and herzegovina": "BA",
  "bosnia and herz": "BA",
  "botswana": "BW",
  "brazil": "BR",
  "brunei": "BN",
  "bulgaria": "BG",
  "burkina faso": "BF",
  "burundi": "BI",
  "cabo verde": "CV",
  "cape verde": "CV",
  "cambodia": "KH",
  "cameroon": "CM",
  "canada": "CA",
  "central african republic": "CF",
  "central african rep": "CF",
  "chad": "TD",
  "chile": "CL",
  "china": "CN",
  "china mainland": "CN",
  "colombia": "CO",
  "comoros": "KM",
  "republic of the congo": "CG",
  "republic of congo": "CG",
  "congo": "CG",
  "democratic republic of the congo": "CD",
  "dr congo": "CD",
  "costa rica": "CR",
  "cote d ivoire": "CI",
  "cote d'ivoire": "CI",
  "cote divoire": "CI",
  "ivory coast": "CI",
  "croatia": "HR",
  "cuba": "CU",
  "cyprus": "CY",
  "czechia": "CZ",
  "czech republic": "CZ",
  "denmark": "DK",
  "djibouti": "DJ",
  "dominica": "DM",
  "dominican republic": "DO",
  "dominican rep": "DO",
  "ecuador": "EC",
  "egypt": "EG",
  "el salvador": "SV",
  "equatorial guinea": "GQ",
  "eq guinea": "GQ",
  "eritrea": "ER",
  "estonia": "EE",
  "eswatini": "SZ",
  "swaziland": "SZ",
  "ethiopia": "ET",
  "fiji": "FJ",
  "finland": "FI",
  "france": "FR",
  "gabon": "GA",
  "gambia": "GM",
  "the gambia": "GM",
  "georgia": "GE",
  "germany": "DE",
  "ghana": "GH",
  "greece": "GR",
  "grenada": "GD",
  "guatemala": "GT",
  "guinea": "GN",
  "guinea bissau": "GW",
  "guyana": "GY",
  "haiti": "HT",
  "honduras": "HN",
  "hungary": "HU",
  "iceland": "IS",
  "india": "IN",
  "indonesia": "ID",
  "iran": "IR",
  "iraq": "IQ",
  "ireland": "IE",
  "israel": "IL",
  "italy": "IT",
  "jamaica": "JM",
  "japan": "JP",
  "jordan": "JO",
  "kazakhstan": "KZ",
  "kenya": "KE",
  "kiribati": "KI",
  "kuwait": "KW",
  "kyrgyzstan": "KG",
  "laos": "LA",
  "lao people s democratic republic": "LA",
  "latvia": "LV",
  "lebanon": "LB",
  "lesotho": "LS",
  "liberia": "LR",
  "libya": "LY",
  "liechtenstein": "LI",
  "lithuania": "LT",
  "luxembourg": "LU",
  "madagascar": "MG",
  "malawi": "MW",
  "malaysia": "MY",
  "maldives": "MV",
  "mali": "ML",
  "malta": "MT",
  "marshall islands": "MH",
  "mauritania": "MR",
  "mauritius": "MU",
  "mexico": "MX",
  "micronesia": "FM",
  "federated states of micronesia": "FM",
  "moldova": "MD",
  "republic of moldova": "MD",
  "monaco": "MC",
  "mongolia": "MN",
  "montenegro": "ME",
  "morocco": "MA",
  "mozambique": "MZ",
  "myanmar": "MM",
  "namibia": "NA",
  "nauru": "NR",
  "nepal": "NP",
  "netherlands": "NL",
  "new zealand": "NZ",
  "nicaragua": "NI",
  "niger": "NE",
  "nigeria": "NG",
  "north korea": "KP",
  "north macedonia": "MK",
  "macedonia": "MK",
  "norway": "NO",
  "oman": "OM",
  "pakistan": "PK",
  "palau": "PW",
  "palestine": "PS",
  "state of palestine": "PS",
  "panama": "PA",
  "papua new guinea": "PG",
  "paraguay": "PY",
  "peru": "PE",
  "philippines": "PH",
  "poland": "PL",
  "portugal": "PT",
  "qatar": "QA",
  "romania": "RO",
  "russia": "RU",
  "russian federation": "RU",
  "rwanda": "RW",
  "saint kitts and nevis": "KN",
  "saint lucia": "LC",
  "saint vincent and the grenadines": "VC",
  "samoa": "WS",
  "san marino": "SM",
  "sao tome and principe": "ST",
  "saudi arabia": "SA",
  "senegal": "SN",
  "serbia": "RS",
  "republic of serbia": "RS",
  "seychelles": "SC",
  "sierra leone": "SL",
  "singapore": "SG",
  "slovakia": "SK",
  "slovenia": "SI",
  "solomon islands": "SB",
  "solomon is": "SB",
  "somalia": "SO",
  "south africa": "ZA",
  "south korea": "KR",
  "south sudan": "SS",
  "s sudan": "SS",
  "spain": "ES",
  "sri lanka": "LK",
  "sudan": "SD",
  "suriname": "SR",
  "sweden": "SE",
  "switzerland": "CH",
  "syria": "SY",
  "syrian arab republic": "SY",
  "tajikistan": "TJ",
  "tanzania": "TZ",
  "united republic of tanzania": "TZ",
  "thailand": "TH",
  "timor leste": "TL",
  "east timor": "TL",
  "togo": "TG",
  "tonga": "TO",
  "trinidad and tobago": "TT",
  "tunisia": "TN",
  "turkey": "TR",
  "turkiye": "TR",
  "turkmenistan": "TM",
  "tuvalu": "TV",
  "uganda": "UG",
  "ukraine": "UA",
  "united arab emirates": "AE",
  "united kingdom": "GB",
  "united kingdom and crown dependencies": "GB",
  "united states": "US",
  "united states of america": "US",
  "uruguay": "UY",
  "uzbekistan": "UZ",
  "vanuatu": "VU",
  "venezuela": "VE",
  "vietnam": "VN",
  "vatican": "VA",
  "vatican city": "VA",
  "holy see": "VA",
  "yemen": "YE",
  "zambia": "ZM",
  "zimbabwe": "ZW",
  "hong kong sar china": "CN",
  "hong kong sar": "CN",
  "hong kong": "CN",
  "macau sar china": "CN",
  "macau sar": "CN",
  "macao sar china": "CN",
  "macau": "CN",
  "macao": "CN",
  "taiwan province of china": "TWN",
  "taiwan": "TWN",
  "kosovo": "XK",
};

export function countryCodeForName(name) {
  return COUNTRY_CODES[normalizeCountryName(name)] || "";
}

export function flagImageUrl(name) {
  const code = countryCodeForName(name);
  return code ? `assets/flags/${code.toLowerCase()}.svg` : "";
}

export function allFlagCodes() {
  return [...new Set(Object.values(COUNTRY_CODES).map((code) => code.toLowerCase()))].sort();
}

export function stripFlag(value) {
  return String(value || "")
    .replace(/[\u{1F1E6}-\u{1F1FF}]{2}/gu, "")
    .trim();
}

function normalizeCountryName(value) {
  return String(value || "")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}
